sbatch slurm/quintessence_inverse_cc_bbb_ov_bundle.sh
sbatch slurm/quintessence_inverse_cc_quint_syn_bbb_ov_bundle.sh
sbatch slurm/quintessence_inverse_cc_hmc_ov_bundle.sh
sbatch slurm/quintessence_inverse_cc_quint_syn_hmc_ov_bundle.sh
