sbatch slurm/lcdm_inverse_cc_lcdm_syn_fcnn_bundle.sh
sbatch slurm/lcdm_inverse_cc_lcdm_syn_nlm_bundle_eb.sh
sbatch slurm/lcdm_inverse_cc_lcdm_syn_nlm_bundle.sh
sbatch slurm/lcdm_inverse_cc_lcdm_syn_bbb_bundle_eb.sh
sbatch slurm/lcdm_inverse_cc_lcdm_syn_bbb_bundle.sh
sbatch slurm/lcdm_inverse_cc_lcdm_syn_hmc_bundle_eb.sh
sbatch slurm/lcdm_inverse_cc_lcdm_syn_hmc_bundle.sh
