sbatch slurm/lcdm_fcnn_bundle.sh
sbatch slurm/lcdm_nlm_bundle_eb.sh
sbatch slurm/lcdm_nlm_bundle.sh
sbatch slurm/lcdm_bbb_bundle_eb.sh
sbatch slurm/lcdm_bbb_bundle.sh
sbatch slurm/lcdm_hmc_bundle_eb.sh
sbatch slurm/lcdm_hmc_bundle.sh
sbatch slurm/cpl_fcnn_bundle.sh
sbatch slurm/cpl_nlm_bundle_eb.sh
sbatch slurm/cpl_nlm_bundle.sh
sbatch slurm/cpl_bbb_bundle_eb.sh
sbatch slurm/cpl_bbb_bundle.sh
sbatch slurm/cpl_hmc_bundle_eb.sh
sbatch slurm/cpl_hmc_bundle.sh
sbatch slurm/quintessence_fcnn_bundle.sh
sbatch slurm/quintessence_nlm_bundle.sh
sbatch slurm/quintessence_bbb_bundle.sh
sbatch slurm/quintessence_hmc_bundle.sh
sbatch slurm/hs_fcnn_bundle.sh
sbatch slurm/hs_clfcnn_bundle.sh
sbatch slurm/hs_nlm_bundle.sh
sbatch slurm/hs_bbb_bundle.sh
sbatch slurm/hs_hmc_bundle.sh
sbatch slurm/lab_fcnn_bundle.sh
sbatch slurm/lab_nlm_bundle.sh
sbatch slurm/lab_bbb_bundle.sh
sbatch slurm/lab_hmc_bundle.sh
