sbatch slurm/plot_data_lcdm_test.sh
sbatch slurm/plot_data_lcdm_train.sh
sbatch slurm/plot_data_lcdm_ood.sh
sbatch slurm/plot_data_lcdm_b_test.sh
sbatch slurm/plot_data_lcdm_b_train.sh
sbatch slurm/plot_data_lcdm_b_ood.sh
sbatch slurm/plot_data_lcdm_eb_test.sh
sbatch slurm/plot_data_lcdm_eb_train.sh
sbatch slurm/plot_data_lcdm_eb_ood.sh
sbatch slurm/plot_data_lcdm_eb_b_test.sh
sbatch slurm/plot_data_lcdm_eb_b_train.sh
sbatch slurm/plot_data_lcdm_eb_b_ood.sh
sbatch slurm/plot_data_cpl_test.sh
sbatch slurm/plot_data_cpl_train.sh
sbatch slurm/plot_data_cpl_ood.sh
sbatch slurm/plot_data_cpl_b_test.sh
sbatch slurm/plot_data_cpl_b_train.sh
sbatch slurm/plot_data_cpl_b_ood.sh
sbatch slurm/plot_data_cpl_eb_test.sh
sbatch slurm/plot_data_cpl_eb_train.sh
sbatch slurm/plot_data_cpl_eb_ood.sh
sbatch slurm/plot_data_cpl_eb_b_test.sh
sbatch slurm/plot_data_cpl_eb_b_train.sh
sbatch slurm/plot_data_cpl_eb_b_ood.sh
sbatch slurm/plot_data_quintessence_test.sh
sbatch slurm/plot_data_quintessence_train.sh
sbatch slurm/plot_data_quintessence_ood.sh
sbatch slurm/plot_data_quintessence_b_test.sh
sbatch slurm/plot_data_quintessence_b_train.sh
sbatch slurm/plot_data_quintessence_b_ood.sh
sbatch slurm/plot_data_hs_test.sh
sbatch slurm/plot_data_hs_train.sh
sbatch slurm/plot_data_hs_ood.sh
sbatch slurm/plot_data_hs_b_test.sh
sbatch slurm/plot_data_hs_b_train.sh
sbatch slurm/plot_data_hs_b_ood.sh
sbatch slurm/plot_data_lab_test.sh
sbatch slurm/plot_data_lab_train.sh
sbatch slurm/plot_data_lab_ood.sh
sbatch slurm/plot_data_lab_b_test.sh
sbatch slurm/plot_data_lab_b_train.sh
sbatch slurm/plot_data_lab_b_ood.sh
sbatch slurm/plot_data_cocoa_test.sh
sbatch slurm/plot_data_cocoa_train.sh
sbatch slurm/plot_data_cocoa_ood.sh
