sbatch slurm/cpl_inverse_cc_cpl_syn_fcnn_bundle.sh
sbatch slurm/cpl_inverse_cc_cpl_syn_nlm_bundle_eb.sh
sbatch slurm/cpl_inverse_cc_cpl_syn_nlm_bundle.sh
sbatch slurm/cpl_inverse_cc_cpl_syn_bbb_bundle_eb.sh
sbatch slurm/cpl_inverse_cc_cpl_syn_bbb_bundle.sh
sbatch slurm/cpl_inverse_cc_cpl_syn_hmc_bundle_eb.sh
sbatch slurm/cpl_inverse_cc_cpl_syn_hmc_bundle.sh
