sbatch slurm/lcdm_inverse_cc_bbb_ov_bundle.sh
sbatch slurm/lcdm_inverse_cc_lcdm_syn_bbb_ov_bundle.sh
sbatch slurm/lcdm_inverse_cc_hmc_ov_bundle.sh
sbatch slurm/lcdm_inverse_cc_lcdm_syn_hmc_ov_bundle.sh
