sbatch slurm/lcdm_fcnn.sh
sbatch slurm/lcdm_nlm_eb.sh
sbatch slurm/lcdm_nlm.sh
sbatch slurm/lcdm_bbb_eb.sh
sbatch slurm/lcdm_bbb.sh
sbatch slurm/lcdm_hmc_eb.sh
sbatch slurm/lcdm_hmc.sh
sbatch slurm/cpl_fcnn.sh
sbatch slurm/cpl_nlm_eb.sh
sbatch slurm/cpl_nlm.sh
sbatch slurm/cpl_bbb_eb.sh
sbatch slurm/cpl_bbb.sh
sbatch slurm/cpl_hmc_eb.sh
sbatch slurm/cpl_hmc.sh
sbatch slurm/quintessence_fcnn.sh
sbatch slurm/quintessence_nlm.sh
sbatch slurm/quintessence_bbb.sh
sbatch slurm/quintessence_hmc.sh
sbatch slurm/hs_fcnn.sh
sbatch slurm/hs_clfcnn.sh
sbatch slurm/hs_nlm.sh
sbatch slurm/hs_bbb.sh
sbatch slurm/hs_hmc.sh
sbatch slurm/lab_fcnn.sh
sbatch slurm/lab_nlm.sh
sbatch slurm/lab_bbb.sh
sbatch slurm/lab_hmc.sh
