sbatch slurm/lcdm_bbb_ov_bundle.sh
sbatch slurm/lcdm_hmc_ov_bundle.sh
sbatch slurm/cpl_bbb_ov_bundle.sh
sbatch slurm/cpl_hmc_ov_bundle.sh
sbatch slurm/quintessence_bbb_ov_bundle.sh
sbatch slurm/quintessence_hmc_ov_bundle.sh
sbatch slurm/hs_bbb_ov_bundle.sh
sbatch slurm/hs_hmc_ov_bundle.sh
sbatch slurm/lab_bbb_ov_bundle.sh
sbatch slurm/lab_hmc_ov_bundle.sh
