sbatch slurm/quintessence_inverse_cc_fcnn_bundle.sh
sbatch slurm/quintessence_inverse_cc_nlm_bundle.sh
sbatch slurm/quintessence_inverse_cc_bbb_bundle.sh
sbatch slurm/quintessence_inverse_cc_hmc_bundle.sh
